25/04/2024 10:10:46|DEBUG|[__init__] Initiating application
25/04/2024 10:10:46|ERROR|[] 'theme'
Traceback (most recent call last):
  File "C:\Users\lenle\Documents\GitHub\DSBG-Shuffle\lib\dsbg_shuffle.py", line 57, in __init__
    if self.settings["theme"] == "light":
       ~~~~~~~~~~~~~^^^^^^^^^
KeyError: 'theme'
25/04/2024 10:10:47|ERROR|[] (<class 'KeyError'>, KeyError('theme'), <traceback object at 0x0000016298FFB780>)
Traceback (most recent call last):
  File "C:\Users\lenle\Documents\GitHub\DSBG-Shuffle\lib\dsbg_shuffle.py", line 5400, in <module>
    app = Application(root)
          ^^^^^^^^^^^^^^^^^
  File "C:\Users\lenle\Documents\GitHub\DSBG-Shuffle\lib\dsbg_shuffle.py", line 57, in __init__
    if self.settings["theme"] == "light":
       ~~~~~~~~~~~~~^^^^^^^^^
KeyError: 'theme'
